# Server
server.port=8080
server.servlet.context-path=/api/auth

# Application
spring.application.name=auth-middleware
spring.profiles.active=${SPRING_PROFILES_ACTIVE:kubernetes}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

# Session (Redis)
session.redis.prefix=moneyflow:session:
session.redis.ttl=86400

